

name: Build, Test and Deploy Final Exam DevOps

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install node_modules
      run: npm install
    - name: Run Unit tests
      run: npm run test:unit
    - name: Display my SoftUni username
      run: echo "Stavrev999"
